## LAB- 2: Write a python script for implementation of vectors, matrices operations.


<b> Vectors Operations </b>

In [1]:
from numpy import array
vector = array([1, 2, 3, 4, 5, 6])
print(vector)

[1 2 3 4 5 6]


In [2]:
a = array([1, 2, 3, 4])
print(a)
b = array([10, 20, 30, 40])
print(b)
c = a + b
print(c)

[1 2 3 4]
[10 20 30 40]
[11 22 33 44]


In [3]:
a = array([100, 200, 300])
print(a)
b = array([50, 150, 250])
print(b)
c = a - b
print(c)

[100 200 300]
[ 50 150 250]
[50 50 50]


In [4]:
a = array([10, 20, 30, 40])
print(a)
b = array([1, 2, 3, 4])
print(b)
c = a * b
print(c)

[10 20 30 40]
[1 2 3 4]
[ 10  40  90 160]


In [5]:
a = array([50, 100, 150, 200])
print(a)
b = array([1, 2, 4, 8])
print(b)
c = a / b
print(c)

[ 50 100 150 200]
[1 2 4 8]
[50.  50.  37.5 25. ]


In [6]:
a = array([10, 20, 30, 40])
print(a)
b = array([1, 2, 3, 4])
print(b)
c = a.dot(b)
print(c)

[10 20 30 40]
[1 2 3 4]
300


In [7]:
a = array([100, 200, 300, 400, 500])
print(a)
s = 2
print(s)
c = s * a
print(c)

[100 200 300 400 500]
2
[ 200  400  600  800 1000]


<b> Matrices Operations </b>

In [8]:
A = array([[10, 20], [30, 40], [50, 60]])
print(A)

[[10 20]
 [30 40]
 [50 60]]


In [9]:
A = array([
[10, 20, 30, 40],
[50, 60, 70, 80]])
print(A)
B = array([
[10, 20, 30, 40],
[50, 60, 70, 80]])
print(B)
C = A + B
print(C)

[[10 20 30 40]
 [50 60 70 80]]
[[10 20 30 40]
 [50 60 70 80]]
[[ 20  40  60  80]
 [100 120 140 160]]


In [10]:
A = array([
[10, 20, 30, 40],
[50, 60, 70, 80]])
print(A)
B = array([
[10, 20, 30, 40],
[50, 60, 70, 80]])
print(B)
C = A - B
print(C)

[[10 20 30 40]
 [50 60 70 80]]
[[10 20 30 40]
 [50 60 70 80]]
[[0 0 0 0]
 [0 0 0 0]]


In [11]:
A = array([
[10, 20, 30, 40],
[50, 60, 70, 80]])
print(A)
B = array([
[10, 20, 30, 40],
[50, 60, 70, 80]])
print(B)
C = A * B
print(C)

[[10 20 30 40]
 [50 60 70 80]]
[[10 20 30 40]
 [50 60 70 80]]
[[ 100  400  900 1600]
 [2500 3600 4900 6400]]


In [12]:
A = array([
[10, 20, 30, 40],
[50, 60, 70, 80]])
print(A)
B = array([
[10, 20, 30, 40],
[50, 60, 70, 80]])
print(B)
C = A / B
print(C)

[[10 20 30 40]
 [50 60 70 80]]
[[10 20 30 40]
 [50 60 70 80]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
B = array([
[1, 2],
[3, 4],
[5, 6]])
print(B)
C = A.dot(B)
print(C)
D = A @ B
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [3 4]
 [5 6]]
[[ 22  28]
 [ 49  64]
 [ 76 100]]
[[ 22  28]
 [ 49  64]
 [ 76 100]]


In [14]:
A = array([
[10, 20],
[30, 40],
[50, 60]])
print(A)
B = array([2, 2])
print(B)
C = A.dot(B)
print(C)

[[10 20]
 [30 40]
 [50 60]]
[2 2]
[ 60 140 220]


In [15]:
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
b = 3
print(b)
C = A * b
print(C)

[[1 2]
 [3 4]
 [5 6]]
3
[[ 3  6]
 [ 9 12]
 [15 18]]
