# NUMPY, VECTOR AND MATRIX

Practise of NumPy, vectors and matrix in python

### PROBLEM SATETMENTS

In [1]:
#importing module of Numpy
import numpy as np

CREATING AND DISPLAYING ARRAY

In [4]:
l =[2.0, 4.0,8.0]
print(type(l))
la = np.array(l, dtype = int)
print(la)
print(type(la))
print(la[0])
print(type(la[0]))
print(la.shape)
print(la.dtype)

<class 'list'>
[2 4 8]
<class 'numpy.ndarray'>
2
<class 'numpy.int32'>
(3,)
int32


FUNCTION TO CREATE ARRAYS

In [5]:
a = np.empty((2,2))
print(a)

[[1.37962320e-306 1.29060871e-306]
 [1.24611266e-306 2.55899112e-307]]


In [6]:
a = np.empty([1,2])
print(a)

[[-2.13101184e-085 -7.62706410e+127]]


In [9]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [11]:
a = np.zeros([3,2])
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
a = np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [13]:
a = np.ones([4])
print(a)

[1. 1. 1. 1.]


COMBINING ARRAYS

In [15]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
print("Vertical Stack")
a3 = np.vstack((a1,a2))
print(a3)
print("Shape of vstack: ",a3.shape)
print("Horizontal Stack")
a3 = np.hstack((a1,a2))
print(a3)
print("Shape of hstack: ",a3.shape)

Vertical Stack
[[1 2 3 4]
 [5 6 7 8]]
Shape of vstack:  (2, 4)
Horizontal Stack
[1 2 3 4 5 6 7 8]
Shape of hstack:  (8,)


ADDITIONAL FUNCTIONS in NUMPY ARRAY

In [18]:
a = np.arange(4)
print("Arange function returns a ndarray: ",a)

Arange function returns a ndarray:  [0 1 2 3]


In [20]:
a = np.eye(4)
print("Eye function returns a N X N matrix with 1 as diagonal and 0 else: \n",a)

Eye function returns a N X N matrix with 1 as diagonal and 0 else: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
a = np.identity(4)
print("identity function returns a N X N matrix with 1 as diagonal and 0 else: \n",a)

identity function returns a N X N matrix with 1 as diagonal and 0 else: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print("DSTACK ")
a3 = np.dstack((a1,a2))
print(a3)
print("Shape after stack: ",a3.shape)


DSTACK 
[[[1 4]
  [2 5]
  [3 6]]]
Shape after stack:  (1, 3, 2)


In [24]:
a4 = np.dsplit(a3,1)
print(a4)

[array([[[1, 4],
        [2, 5],
        [3, 6]]])]


In [31]:
a3 = np.arange(16.0).reshape(2, 2, 4)
print(a3)
a1 = np.dsplit(a3, 2)
print("\nafter dsplit\n")
print(a1)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]

after dsplit

[array([[[ 0.,  1.],
        [ 4.,  5.]],

       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2.,  3.],
        [ 6.,  7.]],

       [[10., 11.],
        [14., 15.]]])]


In [33]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6]])
a3 = np.concatenate((a1,a2))
print(a3)
print("Shape after concatenate: ",a3.shape)

[[1 2]
 [3 4]
 [5 6]]
Shape after concatenate:  (3, 2)


Index, Slice and Reshape NumPy Arrays

CONVERTING LISTS TO NDARRAY

In [36]:
a = [[2,3],[4,9]]
b = np.array(a)
print("List : ",a)
print("Array : \n",b)

List :  [[2, 3], [4, 9]]
Array : 
 [[2 3]
 [4 9]]


INDEXING IN NDARRAY

In [37]:
print(b[1][0])

4


In [38]:
print(b[1,])

[4 9]


In [39]:
print(b[-1][-1])

9


In [44]:
a3 = np.array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])

X, Y = a3[:, :-1], a3[:, -1]
print("X =\n",X)
print("Y =\n",Y)

X =
 [[11 22]
 [44 55]
 [77 88]]
Y =
 [33 66 99]


RESHAPING ARRAY

In [47]:
a1 = np.array([11, 22, 33, 44, 55])
print(a1)
print("shape of a1: ",a1.shape)
print("\n")
a1 = a1.reshape((a1.shape[0], 1))
print(a1)
print("shape of a1: ",a1.shape)

[11 22 33 44 55]
shape of a1:  (5,)


[[11]
 [22]
 [33]
 [44]
 [55]]
shape of a1:  (5, 1)


ARRAY BROADCASTING

In [48]:
a1 = np.array([1,2,3,4])
s = 1
a2 = a1 + s
print(a2)

[2 3 4 5]


In [50]:
a1 = np.array([[1,2,3],[4,5,6]])
s = 2
a2 = a1 + s
print(a2)

[[3 4 5]
 [6 7 8]]


In [51]:
a1 = np.array([[1,1,1],[2,2,2]])
s = np.array([1,2,3])
a2 = a1 + s
print(a2)

[[2 3 4]
 [3 4 5]]


VECTORS

In [52]:
v1 = np.array([1,2,3])
v2 = np.array([1,2,3])
print(v1)

[1 2 3]


In [54]:
v3 = v1 +v2
print(v3)

[2 4 6]


In [55]:
v4 = v1 - v2
print(v4)

[0 0 0]


In [57]:
v5 = v1* v2
print(v5)

[1 4 9]


In [58]:
v6 = v3/v1
print(v6)

[2. 2. 2.]


In [59]:
v7 = v1.dot(v2)
print(v7)

14


In [60]:
v8 = v1 * 0.3
print(v8)

[0.3 0.6 0.9]


VECTOR NORMS

L1 NORM
𝐿1(𝑣)= ‖𝑣‖1=|𝑎1|+|𝑎2|+|𝑎3|

In [63]:
a1 = np.array([4,2,3])
a2 = np.linalg.norm(a1, 1)
print(a2)

9.0


𝐿2(𝑣)=‖𝑣‖2 =sqrt(a1^2 + a2^2 + a3^2)

In [65]:
a2 = np.linalg.norm(a1)
print(a2)

5.385164807134504


MATRIX

In [66]:
a1 = np.array([[2,2,2],[4,4,4]])
a2 = np.array([[1,1,1],[3,3,3]])
print(a1)
print("\n",a2)

[[2 2 2]
 [4 4 4]]

 [[1 1 1]
 [3 3 3]]


MATRIX ADDITITON, SUBTRACTION, MULTIPLICATION , DIVISION

In [67]:
a3 = a1 + a2
print(a3)

[[3 3 3]
 [7 7 7]]


In [68]:
a3 = a1 - a2
print(a3)

[[1 1 1]
 [1 1 1]]


In [69]:
a3 = a1 * a2
print(a3)

[[ 2  2  2]
 [12 12 12]]


In [70]:
a3 = a1 / a2
print(a3)

[[2.         2.         2.        ]
 [1.33333333 1.33333333 1.33333333]]


In [72]:
a4 = np.array([[1,1],[2,2],[3,3]])
a3 = a1.dot(a4)
print(a3)

[[12 12]
 [24 24]]


In [73]:
a3 = a1 @ a4
print(a3)

[[12 12]
 [24 24]]


In [74]:
a3 = a4 * 0.2
print(a3)

[[0.2 0.2]
 [0.4 0.4]
 [0.6 0.6]]


TYPES OF MATRIX

In [75]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
a2 = np.tril(a1)
print(a2)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [78]:
a2 = np.triu(a1)
print(a2)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [80]:
a2 = np.diag(a1)
print(a2)

[1 5 9]


In [81]:
a2 = np.diag(a2)
print(a2)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [82]:
a3 = np.identity(4)
print(a3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [83]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
a2 = a1.T
print(a2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [87]:
a2 = np.linalg.inv(a1)
print(a2)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [88]:
a3= a1.dot(a2)
print(a3)

[[ 0.   1.  -0.5]
 [ 0.   2.  -1. ]
 [ 0.   3.   2.5]]


In [89]:
a4 = np.trace(a1)
print(a4)

15


In [92]:
a4 = np.linalg.det(a1)
print(a4)

-9.51619735392994e-16


In [93]:
A = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)

B = np.linalg.det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16


In [94]:
r = np.linalg.matrix_rank(A)
print(r)

2


In [95]:
A = np.array([[1,2],[1,2],[3,4]])
r = np.linalg.matrix_rank(A)
print(r)

2
